// This file was automatically generated by _codebuilder.py.
// これは _codebuilder.py で自動的に生成されたファイルです。
// 这个文件是由 _codebuilder.py 自动生成的。

import bgi_1 from '../resource/bgi/1.jpg';
import bgi_2 from '../resource/bgi/2.jpg';
import bgi_3 from '../resource/bgi/3.jpg';
import bgi_4 from '../resource/bgi/4.jpg';
import bgi_5 from '../resource/bgi/5.jpg';
import bgi_6 from '../resource/bgi/6.jpg';

export const BackgroundImages = [
  bgi_1,
  bgi_2,
  bgi_3,
  bgi_4,
  bgi_5,
  bgi_6,
];

