import Illust, { IllustType } from '../utils/illust';
import { IllustImages, IllustImageThumbs } from '../resourcesReader/illustReader';
export const illustDesc: Illust[] = 
[
  {
    url: IllustImages[0],
    thumburl: IllustImageThumbs[0],
    title: '絢爛たる沼津市夜景色',
    date: '2024-10-20',
    description: '静岡県沼津市 香貫山',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[1],
    thumburl: IllustImageThumbs[1],
    title: '黒部湖と雪かぶる赤牛岳',
    date: '2024-5-4',
    description: '富山県立山町',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[2],
    thumburl: IllustImageThumbs[2],
    title: '淡島へヨーソロー＾',
    date: '2024-9-10',
    description: '静岡県沼津市',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[3],
    thumburl: IllustImageThumbs[3],
    title: '上高地',
    date: '2023-9-11',
    description: '長野県松本市 上高地',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[4],
    thumburl: IllustImageThumbs[4],
    title: '上高地',
    date: '2023-9-11',
    description: '長野県松本市 上高地',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[5],
    thumburl: IllustImageThumbs[5],
    title: '積雲',
    date: '2023-9-30',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[6],
    thumburl: IllustImageThumbs[6],
    title: '日の出待ち',
    date: '2023-10-22',
    description: '千葉県南房総市',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[7],
    thumburl: IllustImageThumbs[7],
    title: ')－(',
    date: '2024-2-17',
    description: '山梨県身延町下部',
    type: [IllustType.Photo, IllustType.Junrei],
    nsfw: false,
  },
  {
    url: IllustImages[8],
    thumburl: IllustImageThumbs[8],
    title: '本栖湖朝',
    date: '2024-2-18',
    description: '山梨県身延町',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[9],
    thumburl: IllustImageThumbs[9],
    title: '天童アリスちゃん、天童駅だよ',
    date: '2024-3-17',
    description: '山形県天童市',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[10],
    thumburl: IllustImageThumbs[10],
    title: '沼津から身延線経由で帰京途中',
    date: '2024-7-29',
    description: '山梨県南部町',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[11],
    thumburl: IllustImageThumbs[11],
    title: '本栖湖で志摩リンと朝珈琲',
    date: '2024-8-5',
    description: '山梨県',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[12],
    thumburl: IllustImageThumbs[12],
    title: '八丈富士ふれあい牧場',
    date: '2024-9-8',
    description: '東京都八丈町',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[13],
    thumburl: IllustImageThumbs[13],
    title: '遠洋船上',
    date: '2024-9-8',
    description: '御蔵島付近',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[14],
    thumburl: IllustImageThumbs[14],
    title: '自分用Vtuber設定',
    date: '2022-8-18',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[15],
    thumburl: IllustImageThumbs[15],
    title: '高尾山から見た4県',
    date: '2023-10-12',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[16],
    thumburl: IllustImageThumbs[16],
    title: '高尾山から見た4県-色付け',
    date: '2023-10-12',
    description: '',
    type: [IllustType.Photo, IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[17],
    thumburl: IllustImageThumbs[17],
    title: '首都圏鉄道路線略図',
    date: '2023-9-12',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[18],
    thumburl: IllustImageThumbs[18],
    title: '中国省份拓扑图',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[19],
    thumburl: IllustImageThumbs[19],
    title: 'Suviet Union',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[20],
    thumburl: IllustImageThumbs[20],
    title: '？',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[21],
    thumburl: IllustImageThumbs[21],
    title: '秋のるしあ',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[22],
    thumburl: IllustImageThumbs[22],
    title: '架空設定 Chobarian',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Illust, IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[23],
    thumburl: IllustImageThumbs[23],
    title: '渡島半島に抱える函館市',
    date: '2024-3-27',
    description: 'GK801 東京(成田)→旭川',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[24],
    thumburl: IllustImageThumbs[24],
    title: 'フクキタル',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[25],
    thumburl: IllustImageThumbs[25],
    title: 'はあと',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Illust],
    nsfw: true,
  },
  {
    url: IllustImages[26],
    thumburl: IllustImageThumbs[26],
    title: 'ネイチャ',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[27],
    thumburl: IllustImageThumbs[27],
    title: '寧々',
    date: '2024-5-4',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[28],
    thumburl: IllustImageThumbs[28],
    title: 'にこ',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[29],
    thumburl: IllustImageThumbs[29],
    title: 'にこ',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[30],
    thumburl: IllustImageThumbs[30],
    title: 'バレンタイン',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[31],
    thumburl: IllustImageThumbs[31],
    title: 'コハル',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: true,
  },
  {
    url: IllustImages[32],
    thumburl: IllustImageThumbs[32],
    title: 'ターボ',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[33],
    thumburl: IllustImageThumbs[33],
    title: 'みく',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[34],
    thumburl: IllustImageThumbs[34],
    title: '東根室駅',
    date: '2024-3-30',
    description: '北海道根室市',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[35],
    thumburl: IllustImageThumbs[35],
    title: 'ヨハネ',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[36],
    thumburl: IllustImageThumbs[36],
    title: '自分用設定アイコン',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[37],
    thumburl: IllustImageThumbs[37],
    title: '？',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: true,
  },
  {
    url: IllustImages[38],
    thumburl: IllustImageThumbs[38],
    title: 'おっぱい勝負-線画',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: true,
  },
  {
    url: IllustImages[39],
    thumburl: IllustImageThumbs[39],
    title: 'おっぱい勝負',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: true,
  },
  {
    url: IllustImages[40],
    thumburl: IllustImageThumbs[40],
    title: 'ホロライブCN鯖鉄道路線図',
    date: '2020-5-15',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[41],
    thumburl: IllustImageThumbs[41],
    title: '架空',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[42],
    thumburl: IllustImageThumbs[42],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[43],
    thumburl: IllustImageThumbs[43],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[44],
    thumburl: IllustImageThumbs[44],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[45],
    thumburl: IllustImageThumbs[45],
    title: '紺野純子と唐津城',
    date: '2023-10-2',
    description: '佐賀県唐津市',
    type: [IllustType.Photo, IllustType.Junrei],
    nsfw: false,
  },
  {
    url: IllustImages[46],
    thumburl: IllustImageThumbs[46],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[47],
    thumburl: IllustImageThumbs[47],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[48],
    thumburl: IllustImageThumbs[48],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Map],
    nsfw: false,
  },
  {
    url: IllustImages[49],
    thumburl: IllustImageThumbs[49],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Illust],
    nsfw: false,
  },
  {
    url: IllustImages[50],
    thumburl: IllustImageThumbs[50],
    title: '天の川 in 八丈富士',
    date: '2024-9-10',
    description: '東京都八丈町',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[51],
    thumburl: IllustImageThumbs[51],
    title: '青島市スカイライン',
    date: '2024-9-10',
    description: '山東省青島市市南区',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[52],
    thumburl: IllustImageThumbs[52],
    title: '太白山登山道から仙台市を眺望',
    date: '2024-3-18',
    description: '宮城県仙台市太白区',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[53],
    thumburl: IllustImageThumbs[53],
    title: '「色づく世界の明日から」',
    date: '2023-10-3',
    description: '長崎県長崎市',
    type: [IllustType.Photo, IllustType.Junrei],
    nsfw: false,
  },
  {
    url: IllustImages[54],
    thumburl: IllustImageThumbs[54],
    title: '',
    date: '',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[55],
    thumburl: IllustImageThumbs[55],
    title: '',
    date: '2022-11-05',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[56],
    thumburl: IllustImageThumbs[56],
    title: '',
    date: '2022-11-29',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[57],
    thumburl: IllustImageThumbs[57],
    title: '',
    date: '2023-04-29',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[58],
    thumburl: IllustImageThumbs[58],
    title: '',
    date: '2023-05-02',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[59],
    thumburl: IllustImageThumbs[59],
    title: '',
    date: '2023-09-02',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[60],
    thumburl: IllustImageThumbs[60],
    title: '',
    date: '2023-09-03',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[61],
    thumburl: IllustImageThumbs[61],
    title: '',
    date: '2023-09-09',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[62],
    thumburl: IllustImageThumbs[62],
    title: '',
    date: '2023-10-01',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[63],
    thumburl: IllustImageThumbs[63],
    title: '',
    date: '2023-10-01',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[64],
    thumburl: IllustImageThumbs[64],
    title: '',
    date: '2023-10-02',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[65],
    thumburl: IllustImageThumbs[65],
    title: '',
    date: '2023-10-02',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[66],
    thumburl: IllustImageThumbs[66],
    title: '',
    date: '2023-10-05',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[67],
    thumburl: IllustImageThumbs[67],
    title: '',
    date: '2023-10-07',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[68],
    thumburl: IllustImageThumbs[68],
    title: '',
    date: '2023-10-21',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[69],
    thumburl: IllustImageThumbs[69],
    title: '',
    date: '2023-11-23',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[70],
    thumburl: IllustImageThumbs[70],
    title: '',
    date: '2023-11-24',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[71],
    thumburl: IllustImageThumbs[71],
    title: '',
    date: '2023-12-07',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[72],
    thumburl: IllustImageThumbs[72],
    title: '',
    date: '2023-12-08',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[73],
    thumburl: IllustImageThumbs[73],
    title: '',
    date: '2023-12-10',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[74],
    thumburl: IllustImageThumbs[74],
    title: '',
    date: '2023-12-10',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[75],
    thumburl: IllustImageThumbs[75],
    title: '',
    date: '2023-12-23',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[76],
    thumburl: IllustImageThumbs[76],
    title: '',
    date: '2023-12-25',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[77],
    thumburl: IllustImageThumbs[77],
    title: '',
    date: '2024-03-17',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[78],
    thumburl: IllustImageThumbs[78],
    title: '',
    date: '2024-03-30',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[79],
    thumburl: IllustImageThumbs[79],
    title: '',
    date: '2024-04-20',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[80],
    thumburl: IllustImageThumbs[80],
    title: '',
    date: '2024-04-20',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[81],
    thumburl: IllustImageThumbs[81],
    title: '',
    date: '2024-05-01',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[82],
    thumburl: IllustImageThumbs[82],
    title: '',
    date: '2024-05-01',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[83],
    thumburl: IllustImageThumbs[83],
    title: '',
    date: '2024-05-02',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[84],
    thumburl: IllustImageThumbs[84],
    title: '',
    date: '2024-05-03',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[85],
    thumburl: IllustImageThumbs[85],
    title: '',
    date: '2024-05-03',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[86],
    thumburl: IllustImageThumbs[86],
    title: '',
    date: '2024-05-04',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[87],
    thumburl: IllustImageThumbs[87],
    title: '',
    date: '2024-05-04',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[88],
    thumburl: IllustImageThumbs[88],
    title: '',
    date: '2024-05-28',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[89],
    thumburl: IllustImageThumbs[89],
    title: '',
    date: '2024-06-14',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[90],
    thumburl: IllustImageThumbs[90],
    title: '',
    date: '2024-06-16',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[91],
    thumburl: IllustImageThumbs[91],
    title: '',
    date: '2024-06-27',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[92],
    thumburl: IllustImageThumbs[92],
    title: '',
    date: '2024-06-29',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[93],
    thumburl: IllustImageThumbs[93],
    title: '',
    date: '2024-07-07',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[94],
    thumburl: IllustImageThumbs[94],
    title: '',
    date: '2024-07-08',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[95],
    thumburl: IllustImageThumbs[95],
    title: '',
    date: '2024-07-09',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[96],
    thumburl: IllustImageThumbs[96],
    title: '',
    date: '2024-07-09',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[97],
    thumburl: IllustImageThumbs[97],
    title: '',
    date: '2024-07-09',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[98],
    thumburl: IllustImageThumbs[98],
    title: '',
    date: '2024-07-27',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[99],
    thumburl: IllustImageThumbs[99],
    title: '',
    date: '2024-08-10',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[100],
    thumburl: IllustImageThumbs[100],
    title: '',
    date: '2024-09-08',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[101],
    thumburl: IllustImageThumbs[101],
    title: '',
    date: '2024-09-08',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[102],
    thumburl: IllustImageThumbs[102],
    title: '',
    date: '2024-09-09',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[103],
    thumburl: IllustImageThumbs[103],
    title: '',
    date: '2024-09-10',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[104],
    thumburl: IllustImageThumbs[104],
    title: '',
    date: '2024-09-11',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[105],
    thumburl: IllustImageThumbs[105],
    title: '',
    date: '2024-09-21',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[106],
    thumburl: IllustImageThumbs[106],
    title: '',
    date: '2024-10-25',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[107],
    thumburl: IllustImageThumbs[107],
    title: '',
    date: '2024-10-26',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[108],
    thumburl: IllustImageThumbs[108],
    title: '',
    date: '2024-10-26',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[109],
    thumburl: IllustImageThumbs[109],
    title: '',
    date: '2024-10-27',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[110],
    thumburl: IllustImageThumbs[110],
    title: '',
    date: '2024-10-29',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
  {
    url: IllustImages[111],
    thumburl: IllustImageThumbs[111],
    title: '',
    date: '2024-11-09',
    description: '',
    type: [IllustType.Photo],
    nsfw: false,
  },
];
