import { ProjectIcons } from '../resourcesReader/projectIconReader';
import { DevState } from '../utils/project';
import { StaticProject } from '../utils/staticProject';

export const static_projects_zh_cn: StaticProject[] = [
  {
    name: 'WOTAGEIPEDIA - ヲタ芸百科',
    url: 'http://wotagei.elpwc.com',
    github: 'https://github.com/elpwc/wotageipedia',
    status: DevState.Developing,
    desc: '目的是创造一个将各个视频网站上零散分布的技连视频中的技系统地登记、归类在一起，能方便又快捷地按照 「技名・系・动作(?)・本家・...」 等各种信息查技的网站。解决wota艺圈内查技难，ori技容易埋没在视频站，界隈难以联络到的问题',
    image: './images/wotageipedia.png',
    imageWidth: '40%',
    tags: 'React, Python, TypeScript, AntDesign',
    icon: ProjectIcons.i_wotagei,
  },
  {
    name: 'wniko homepage',
    url: '',
    github: 'https://github.com/elpwc/wniko-homepage',
    status: DevState.Developing,
    desc: '真正的支持留言，博客，项目展示等等功能的个人主页',
    image: '',
    tags: 'React, Nest.js, TypeORM, TypeScript, AntDesign',
  },
  {
    name: 'XP系统测试器',
    url: 'http://www.elpwc.com/test',
    github: 'https://github.com/elpwc/seiheki-test',
    status: DevState.Developing,
    desc: '一个提供XP系统维护功能的在线工具(?)',
    image: './images/xp.png',
    imageWidth: '8%',
    tags: 'Svelte, TypeScript, PHP',
  },
  {
    name: '吃掉小涩图',
    url: 'http://www.elpwc.com/eatsetu',
    github: 'https://github.com/elpwc/EatSetu',
    status: DevState.Done,
    desc: '跟风作()',
    image: '',
    tags: 'PHP, JS',
  },
  {
    name: '⊌PC Leaver .web - 批量出校请假服务',
    url: 'http://www.elpwc.com/upcleaver/',
    github: 'https://github.com/elpwc/UPC-Leaver.web',
    status: DevState.MaintainingStopped,
    desc: '',
    image: '',
    tags: 'PHP, JS, BootStrap',
  },
  {
    name: 'ANIME-SEIRI.web',
    url: 'http://www.elpwc.com/animeseiri',
    github: 'https://github.com/elpwc/ANIME-SEIRI.web',
    status: DevState.Deprecated,
    desc: '',
    image: '',
    tags: 'PHP, SASS, BootStrap',
  },
  {
    name: 'City Counter Game',
    url: '',
    github: 'https://github.com/elpwc/CityCounterGame',
    status: DevState.Planning,
    desc: '猜城市名的web游戏',
    image: '',
  },
  {
    name: '웹페이지 漢字 콘버터 Chrome ext',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '将韩文页面内汉字词全部转换为汉字的chrome插件',
    image: '',
  },
  {
    name: '地名词源收录站',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '',
    image: '',
  },
  {
    name: 'CJKVR对照图在线排版',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '',
    image: '',
  },
  {
    name: '汉文训读在线排版',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '',
    image: '',
  },
];

export const static_projects_ja: StaticProject[] = [
  {
    name: 'OnlineEldenRingMap - 老头环地图',
    url: 'http://www.elpwc.com/eldenringmap',
    github: 'https://github.com/elpwc/EldenRingOnlineMap',
    status: DevState.Done,
    desc: '',
    image: '',
    imageWidth: '',
    tags: 'Svelte, TypeScript, PHP, Leaflet',
    icon: ProjectIcons.i_elden,
  },
  {
    name: 'maiweb',
    url: 'https://www.elpwc.com/dev/maiweb/',
    github: 'https://github.com/elpwc/maiweb',
    status: DevState.Developing,
    desc: '',
    image: '',
    imageWidth: '',
    tags: 'React, TypeScript, Canvas',
  },
  {
    name: 'react-maiweb',
    url: '',
    github: 'https://github.com/elpwc/maiweb',
    status: DevState.Done,
    desc: '',
    image: '',
    imageWidth: '',
    tags: 'React, TypeScript, Canvas',
  },
  {
    name: 'WOTAGEIPEDIA - ヲタ芸百科',
    url: 'http://wotagei.elpwc.com',
    github: 'https://github.com/elpwc/wotageipedia',
    status: DevState.Developing,
    desc: '動画サイトにちらほら分布しているヲタ芸のサビ技動画を系統的に登録し、分類することで、「技名・系・動き(仮)・本家・...」でいろんな情報を経由して検索することを可能にするのを目指しているプロジェクトです。',
    image: './images/wotageipedia.png',
    imageWidth: '40%',
    tags: 'React, Python, TypeScript, AntDesign',
    icon: ProjectIcons.i_wotagei,
  },
  {
    name: 'wniko homepage',
    url: '',
    github: 'https://github.com/elpwc/wniko-homepage',
    status: DevState.Developing,
    desc: 'すなわち個人ページの事',
    image: '',
    tags: 'React, Nest.js, TypeORM, TypeScript',
  },
  {
    name: 'Kikaku',
    url: 'https://www.elpwc.com/kikaku',
    github: 'https://github.com/elpwc/kikaku',
    status: DevState.Done,
    desc: 'すなわち個人ページの事',
    image: '',
    tags: 'React, Nest.js, TypeORM, TypeScript',
  },
  {
    name: '市町村行脚',
    url: '',
    github: '',
    status: DevState.Developing,
    desc: 'すなわち個人ページの事',
    image: '',
    tags: 'React, Nest.js, TypeORM, TypeScript',
  },
  {
    name: 'XP系统测试器',
    url: 'http://www.elpwc.com/test',
    github: 'https://github.com/elpwc/seiheki-test',
    status: DevState.Developing,
    desc: '一个提供XP系统维护功能的在线工具(?)',
    image: './images/xp.png',
    imageWidth: '8%',
    tags: 'Svelte, TypeScript, PHP',
  },
  {
    name: '吃掉小涩图',
    url: 'http://www.elpwc.com/eatsetu',
    github: 'https://github.com/elpwc/EatSetu',
    status: DevState.Done,
    desc: '跟风作()',
    image: '',
    tags: 'PHP, JS',
  },
  {
    name: '⊌PC Leaver .web - 批量出校请假服务',
    url: 'http://www.elpwc.com/upcleaver/',
    github: 'https://github.com/elpwc/UPC-Leaver.web',
    status: DevState.MaintainingStopped,
    desc: '',
    image: '',
    tags: 'PHP, JS, BootStrap',
  },
  {
    name: 'ANIME-SEIRI.web',
    url: 'http://www.elpwc.com/animeseiri',
    github: 'https://github.com/elpwc/ANIME-SEIRI.web',
    status: DevState.Deprecated,
    desc: '',
    image: '',
    tags: 'PHP, SASS, BootStrap',
  },
  {
    name: 'City Counter Game',
    url: '',
    github: 'https://github.com/elpwc/CityCounterGame',
    status: DevState.Planning,
    desc: '猜城市名的web游戏',
    image: '',
  },
  {
    name: '웹페이지 漢字 콘버터 Chrome ext',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '将韩文页面内汉字词全部转换为汉字的chrome插件',
    image: '',
  },
  {
    name: '地名词源收录站',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '',
    image: '',
  },
  {
    name: 'CJKVR对照图在线排版',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '',
    image: '',
  },
  {
    name: '汉文训读在线排版',
    url: '',
    github: '',
    status: DevState.Planning,
    desc: '',
    image: '',
  },
];
